### PR TITLE
Added lazy injection feature to Container module

### PR DESCRIPTION
**Pull request by gskierk**
This PR introduces lazy injection to Container module.

```php
Container\set(
    'lazyServiceName',
    function() {
        return 'lazyService';
    }
);
```
```php
Container\get('lazyServiceName'); // it returns 'lazyService'!
```

### CODE REVIEW

**Comment by leocavalcante** [comment]
Hey, thank you very much for the PR!
Can you please fix the errors pointed by Psalm?
If you need some help or have any questions, feel free to ask!

**Review by leocavalcante — CHANGES_REQUESTED** [review]
Hey, thank you very much for the PR!
Can you please fix the errors pointed by Psalm?
If you need some help or have any questions, feel free to ask!

**Comment by gskierk** [comment]
> Hey, thank you very much for the PR!
> Can you please fix the errors pointed by Psalm?
> If you need some help or have any questions, feel free to ask!

It was my first touch with Psalm, but I finally managed to fix those errors... 😅

**Review by leocavalcante — APPROVED** [review]

**Comment by leocavalcante** [comment]
Hehe, great, thanks!! I'm glad to have contributions to Siler and if it can help people learning new things it is even better.

**Pull request merged**
