### PR TITLE
GraphQL Annotations

### PR DESCRIPTION
**Pull request by leocavalcante**
- [x] Object Types
- [x] Scalar Types
- [x] Enumeration Types
- [x] Lists and Non-Null
- [x] Interfaces
- [x] Unions
- [x] Mutations and Input Types
- [x] Directives
- [x] **Tests**

### CODE REVIEW

**Comment by jordanbrauer** [comment]
Does this replace the current way of configuring fields and resolvers?

**Comment by leocavalcante** [comment]
@jordanbrauer No, the current way of mapping resolvers from the SDL will still be fully supported, this is an alternative when you want to do the other way around, when you want to start from PHP then have a SDL generated.
After using Siler/GraphQL quite a lot I felt this. With this you don't need to write the same thing twice (even three times if you don't use something like graphql-codegen to build your TS front).

Instead of
```graphql
type Todo {
    id: ID!
    title: String!
    done: Boolean!
}
```
And also:
```php
class Todo {
    public int $id;
    public string $title;
    public bool $done;
}
```

You can just:

```php
/** @ObjectType */
class Todo {
    /** @Field(type="ID") */
    public int $id;
    /** @Field(type="String") */
    public string $title;
    /** @Field(type="Boolean") */
    public bool $done;
}
```
Then reason about GraphQL schema and PHP business rules on the same place.

Also you will be able to have typed input types:

```php
/** @InputType*/
class TodoInput {
    /** @Field(type="String") */
    public string $title;
    /** @Field(type="Boolean", nullable=true) */
    public bool $done = false;
}
```
This is not currently possible, today you just define your input on the SDL and grab scalars from `$args`.
I mean, you can have a type for your input in PHP, but hasn't any guarantee that is a 1:1 match to your SDL, if you change a property on SDL you have to remember to change the PHP too, the same goes for the other types.

You can strictly tie a PHP type to every piece of GraphQL code without writing twice (DRY).

**Comment by jordanbrauer** [comment]
> No, the current way of mapping resolvers from the SDL will still be fully supported,

🙏 🎉 🎊 awesome, thank you for the fast & detailed reply. Here is my 2-cents on the rest (but don't take it as me disagreeing/arguing 😁)

> this is an alternative when you want to do the other way around, when you want to start from PHP then have a SDL generated.
> After using Siler/GraphQL quite a lot I felt this. With this you don't need to write the same thing twice (even three times if you don't use something like graphql-codegen to build your TS front).
>
> Instead of
>
> ```graphql
> # ...
> ```
> And also:
> 
> ```php
> # ...
> ```
> You can just:
> ```php
> # ...
> ```
> Then reason about GraphQL schema and PHP business rules on the same place.

Ah, yeah.. I see what you're saying. From my experience, this kind of repetition is acceptable, given they are different layers of your application, and thus usually do not map available fields/inputs 1:1. An example of what I mean could be the common misconception/pitfall for beginners with GraphQL; that the schema has to (or should) map their database/model fields 1:1 – this is obviously not true, and arguably bad design.

That being said, everyone has a different idea of what might be too much repetition, and maybe an API _wants_ to map it's database/models 1:1 in the schema by design!

> Also you will be able to have typed input types:
> 
> ```php
> # ...
> ```
> This is not currently possible, today you just define your input on the SDL and grab scalars from `$args`.
> I mean, you can have a type for your input in PHP, but hasn't any guarantee that is a 1:1 match to your SDL, if you change a property on SDL you have to remember to change the PHP too, the same goes for the other types.
>
> You can strictly tie a PHP type to every piece of GraphQL code without writing twice (DRY).

Interesting. I personally have not yet encountered this problem at my day-job, or in another app I am working on (where I am using Siler). In both cases, the schema serves as a source of truth between the server and client. Schema changes only come from a backend developer, where deprecating forward any old/new/removed fields is part of the development process. Clients are then free to upgrade on their own, without breaking. Of course this isn't perfect, and dead fields on the server _can_ still be returned from resolvers, if the developer and code reviewer are not vigilant enough.

On the app which I am using Siler, I solve the `$args` type issue through my database models. I've pulled in Laravel's Eloquent package as a way to back the GraphQL types. I am not sure how familiar you are with Laravel, but Eloquent models have "mutators" and "accessors", which are methods that proxy calls to a property on the model class. Because an accessor (`$user->username`) or mutator (`$user->username = 'foobar'`) is a method, we can type hint the arguments to those – effectively delegating those scalar checks to another method, instead of manually mapping it, or using annotations.

There is very little duplication with this, because typically the schema exposes computed properties ("accessors") as opposed to the raw fields from database or properties on the model class.

---

Anyways ... thanks again for all the great work on this library!

**Comment by leocavalcante** [comment]
Thank you for bringing this, goods points over there. Having a SDL as top source where clients and servers mutually agrees is something to have in consideration. Well, anyhow, with addition of Annotations we can have in Siler both ways to go: SDL->PHP or PHP->SDL and users another option to choose what strategy fits better.

**Pull request merged**
