### PR TITLE
Replace WebSocket clients

### LINKED ISSUE #223: Replace WebSocket client support
GraphQL publish depends on https://github.com/ratchetphp/Pawl to broadcast the websocket server about subscription data updates and this:
- Brings the entire ReactPHP lib (almost)
- Forces an asynchronous API without need
- But mainly: **doesn't work with Swoole co-routines**

We should move to https://github.com/Textalk/websocket-php

### PR DESCRIPTION
**Pull request by leocavalcante**
Closes #223

### CODE REVIEW

**Comment by lemonbrain-mk** [comment]
I'm using this package in my own package https://github.com/lemonbrain-mk/graphql_websocket unfortunately cause, the `"textalk/websocket": "^1.2",` is a dev dependency, it gets not loaded. and all the websocket things are not working. Is it possible to move it in the required section?

**Comment by lemonbrain-mk** [comment]
And maybe in the doc it should be written that `GraphQL\subscription`  is deprecated

https://siler.leocavalcante.dev/graphql/

**Comment by lemonbrain-mk** [comment]
I did it now int the `GraphQL\GraphQL` File on line 347

```
    $options = [
        'headers' => [
            'Sec-WebSocket-Protocol' => 'graphql-ws'
        ]
    ];

    $client = new Client($ws_endpoint, $options);
```

**Comment by leocavalcante** [comment]
>  the `"textalk/websocket": "^1.2"`, is a dev dependency, it gets not loaded. Is it possible to move it in the required section?

All Siler's "dependencies" are peer dependencies, you have to explicitly declare alongside with `leocavalcante/sielr` the same you did for `webonyx/graphql-php` and `cboden/ratchet`.

> I found a problem with the client not sending the sec-websocket-protocol. is there a workaround? I did it now int the GraphQL\GraphQL File on line 347

Thank you very much for reporting and presenting the solution. I'll open a new issue.

**Pull request merged**
